# Generated by Django 4.2 on 2024-09-21 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_meja', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instansi', models.CharField(max_length=128)),
                ('nama', models.CharField(max_length=128)),
                ('meja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.meja')),
            ],
        ),
    ]
