# Generated by Django 4.2 on 2024-09-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meja',
            options={'verbose_name': 'Meja', 'verbose_name_plural': 'Meja'},
        ),
        migrations.AlterModelOptions(
            name='tamu',
            options={'verbose_name': 'Tamu', 'verbose_name_plural': 'Tamu'},
        ),
        migrations.AddField(
            model_name='tamu',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='tamu',
            name='nama',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
