# Generated by Django 4.2 on 2024-09-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0002_alter_meja_options_alter_tamu_options_tamu_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamu',
            name='nama',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
