# Generated by Django 4.2 on 2024-09-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0003_alter_tamu_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamu',
            name='rand_code',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
