# Generated by Django 4.2 on 2024-09-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0004_tamu_rand_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamu',
            name='rand_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
