# Generated by Django 4.2 on 2024-09-23 09:09

import RegistrationApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0005_alter_tamu_rand_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamu',
            name='slug',
            field=models.SlugField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='tamu',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=RegistrationApp.models.get_qr_code_upload_path),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('tamu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.tamu')),
            ],
        ),
    ]
