# Generated by Django 4.2 on 2024-09-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0006_tamu_slug_alter_tamu_qr_code_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamu',
            name='sudah_checkin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
