# Generated by Django 5.1.1 on 2026-05-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0008_event_alter_tamu_qr_code_tamu_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='event_covers/'),
        ),
    ]
