# Generated by Django 5.1.1 on 2026-05-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0009_event_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamu',
            name='instansi',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
