# Generated by Django 5.1.1 on 2026-05-07 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0010_alter_tamu_instansi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='tamu',
        ),
        migrations.AlterUniqueTogether(
            name='tamu',
            unique_together={('nama', 'instansi')},
        ),
        migrations.AlterField(
            model_name='tamu',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.event'),
        ),
        migrations.AlterField(
            model_name='tamu',
            name='meja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.meja'),
        ),
        migrations.CreateModel(
            name='Registrasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('rand_code', models.CharField(blank=True, max_length=8, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=8)),
                ('sudah_checkin', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftaran_list', to='RegistrationApp.event')),
                ('meja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.meja')),
                ('tamu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_event', to='RegistrationApp.tamu')),
            ],
            options={
                'verbose_name': 'Pendaftaran',
                'verbose_name_plural': 'Pendaftaran',
                'unique_together': {('event', 'tamu')},
            },
        ),
        migrations.AddField(
            model_name='checkin',
            name='pendaftaran',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.registrasi'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tamu',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='tamu',
            name='rand_code',
        ),
        migrations.RemoveField(
            model_name='tamu',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tamu',
            name='sudah_checkin',
        ),
    ]
