# Generated by Django 5.1.1 on 2026-05-07 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0014_alter_tamu_event_alter_tamu_meja'),
    ]

    operations = [
        migrations.AddField(
            model_name='meja',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.event'),
            preserve_default=False,
        ),
    ]
