# Generated by Django 5.1.1 on 2026-05-07 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0016_alter_tamu_event_alter_tamu_meja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamu',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.event'),
        ),
        migrations.AlterField(
            model_name='tamu',
            name='meja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RegistrationApp.meja'),
        ),
    ]
