# Generated by Django 5.1.1 on 2026-05-08 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0017_alter_tamu_event_alter_tamu_meja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrasi',
            name='meja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RegistrationApp.meja'),
        ),
    ]
