# Generated by Django 5.1.1 on 2026-05-08 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0018_alter_registrasi_meja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamu',
            name='event',
        ),
        migrations.RemoveField(
            model_name='tamu',
            name='meja',
        ),
    ]
