# Generated by Django 5.1.1 on 2026-05-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0019_remove_tamu_event_remove_tamu_meja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrasi',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='registrasi',
            name='rand_code',
        ),
        migrations.RemoveField(
            model_name='registrasi',
            name='slug',
        ),
        migrations.AddField(
            model_name='tamu',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='tamu',
            name='rand_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='tamu',
            name='slug',
            field=models.SlugField(blank=True, max_length=8),
        ),
    ]
