# Generated by Django 5.1.1 on 2026-05-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0020_remove_registrasi_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamu',
            name='rand_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tamu',
            name='slug',
            field=models.SlugField(blank=True, max_length=8, null=True),
        ),
    ]
