# Generated by Django 5.1.1 on 2026-05-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0021_alter_tamu_rand_code_alter_tamu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrasi',
            name='peserta',
            field=models.TextField(blank=True, null=True, verbose_name='Daftar Peserta Tambahan'),
        ),
    ]
